/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source is under src/.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CodeFilePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  showHeader: true,
  maxFileSizeKb: 512,
  langOverrides: {}
};
function overridesToText(overrides) {
  return Object.entries(overrides).map(([ext, lang]) => `${ext}=${lang}`).join("\n");
}
function textToOverrides(text) {
  const out = {};
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#"))
      continue;
    const match = trimmed.match(/^([^=:]+)[=:](.+)$/);
    if (!match)
      continue;
    const ext = match[1].trim().toLowerCase().replace(/^\./, "");
    const lang = match[2].trim();
    if (ext && lang)
      out[ext] = lang;
  }
  return out;
}
var CodeFileSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Show file header").setDesc("Display a clickable header with the file path above each embed.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showHeader).onChange(async (value) => {
        this.plugin.settings.showHeader = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Max file size (KB)").setDesc("Refuse to embed files larger than this. Use 0 for no limit.").addText(
      (text) => text.setValue(String(this.plugin.settings.maxFileSizeKb)).onChange(async (value) => {
        const n = parseInt(value, 10);
        this.plugin.settings.maxFileSizeKb = Number.isFinite(n) && n >= 0 ? n : 0;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Language overrides").setDesc("One per line as ext=language, e.g. abap=abap. Overrides the built-in map.").addTextArea((area) => {
      area.setValue(overridesToText(this.plugin.settings.langOverrides)).onChange(async (value) => {
        this.plugin.settings.langOverrides = textToOverrides(value);
        await this.plugin.saveSettings();
      });
      area.inputEl.rows = 6;
      area.inputEl.addClass("codefile-overrides-input");
    });
  }
};

// src/parser.ts
function parseCodeFileSource(input) {
  const raw = (input ?? "").trim();
  if (!raw)
    return null;
  let linkpath = raw;
  let start;
  let end;
  const rangeMatch = raw.match(/^(.*?):(\d+)(?:-(\d+))?\s*$/);
  if (rangeMatch) {
    linkpath = rangeMatch[1].trim();
    start = parseInt(rangeMatch[2], 10);
    end = rangeMatch[3] !== void 0 ? parseInt(rangeMatch[3], 10) : start;
  }
  linkpath = linkpath.replace(/^\[\[/, "").replace(/\]\]$/, "").trim();
  linkpath = linkpath.replace(/^["']/, "").replace(/["']$/, "").trim();
  if (!linkpath)
    return null;
  return { linkpath, start, end };
}

// src/CodeFileChild.ts
var import_obsidian2 = require("obsidian");

// src/langMap.ts
var DEFAULT_LANG_MAP = {
  abap: "abap",
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  ts: "typescript",
  jsx: "jsx",
  tsx: "tsx",
  py: "python",
  rb: "ruby",
  java: "java",
  c: "c",
  h: "c",
  cpp: "cpp",
  cxx: "cpp",
  cc: "cpp",
  hpp: "cpp",
  cs: "csharp",
  go: "go",
  rs: "rust",
  php: "php",
  swift: "swift",
  kt: "kotlin",
  kts: "kotlin",
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  ps1: "powershell",
  sql: "sql",
  json: "json",
  jsonc: "json",
  yaml: "yaml",
  yml: "yaml",
  xml: "xml",
  html: "html",
  htm: "html",
  css: "css",
  scss: "scss",
  sass: "sass",
  less: "less",
  md: "markdown",
  markdown: "markdown",
  toml: "toml",
  ini: "ini",
  cfg: "ini",
  lua: "lua",
  r: "r",
  scala: "scala",
  dart: "dart",
  pl: "perl",
  pm: "perl",
  vue: "vue",
  svelte: "svelte",
  dockerfile: "docker",
  makefile: "makefile"
};
function getExtension(path) {
  const base = path.split(/[\\/]/).pop() ?? "";
  const idx = base.lastIndexOf(".");
  if (idx <= 0) {
    return base.toLowerCase();
  }
  return base.slice(idx + 1).toLowerCase();
}
function extToLang(ext, overrides = {}) {
  const key = ext.toLowerCase().replace(/^\./, "");
  return overrides[key] ?? DEFAULT_LANG_MAP[key] ?? key;
}

// src/CodeFileChild.ts
var BINARY_RE = /[\x00-\x08\x0e-\x1f]/;
var CodeFileChild = class extends import_obsidian2.MarkdownRenderChild {
  constructor(plugin, ctx, containerEl, ref) {
    super(containerEl);
    this.plugin = plugin;
    this.ctx = ctx;
    this.ref = ref;
    this.targetPath = null;
  }
  onload() {
    void this.render();
    this.registerEvent(
      this.plugin.app.vault.on("modify", (file) => {
        if (this.targetPath && file.path === this.targetPath)
          void this.render();
      })
    );
    this.registerEvent(
      this.plugin.app.vault.on(
        "rename",
        (file, oldPath) => {
          if (this.targetPath && oldPath === this.targetPath) {
            this.targetPath = file.path;
            void this.render();
          }
        }
      )
    );
  }
  async render() {
    const el = this.containerEl;
    el.empty();
    el.addClass("codefile-embed");
    if (!this.ref) {
      this.renderError("informe o caminho do arquivo");
      return;
    }
    const app = this.plugin.app;
    const dest = app.metadataCache.getFirstLinkpathDest(
      this.ref.linkpath,
      this.ctx.sourcePath
    );
    if (!(dest instanceof import_obsidian2.TFile)) {
      this.renderError(`arquivo n\xE3o encontrado: ${this.ref.linkpath}`);
      return;
    }
    this.targetPath = dest.path;
    const maxKb = this.plugin.settings.maxFileSizeKb;
    if (maxKb > 0 && dest.stat.size > maxKb * 1024) {
      this.renderError(
        `arquivo grande demais (${Math.round(dest.stat.size / 1024)} KB > ${maxKb} KB)`
      );
      return;
    }
    let content;
    try {
      content = await app.vault.cachedRead(dest);
    } catch (e) {
      this.renderError(`erro ao ler arquivo: ${String(e)}`);
      return;
    }
    if (BINARY_RE.test(content)) {
      this.renderError("arquivo parece bin\xE1rio");
      return;
    }
    let rangeNote = "";
    if (this.ref.start !== void 0) {
      const lines = content.split("\n");
      let s = this.ref.start;
      let e = this.ref.end ?? this.ref.start;
      if (s > e)
        [s, e] = [e, s];
      if (s < 1)
        s = 1;
      if (s > lines.length) {
        rangeNote = " (faixa fora do arquivo \u2014 mostrando tudo)";
      } else {
        content = lines.slice(s - 1, Math.min(e, lines.length)).join("\n");
      }
    }
    const lang = extToLang(
      getExtension(dest.path),
      this.plugin.settings.langOverrides
    );
    if (this.plugin.settings.showHeader) {
      this.renderHeader(dest, rangeNote);
    }
    const body = el.createDiv({ cls: "codefile-body" });
    const fence = pickFence(content);
    const md = `${fence}${lang}
${content}
${fence}`;
    await import_obsidian2.MarkdownRenderer.render(app, md, body, this.ctx.sourcePath, this);
  }
  renderHeader(file, rangeNote) {
    const header = this.containerEl.createDiv({ cls: "codefile-header" });
    let label = file.path;
    if (this.ref?.start !== void 0) {
      const s = this.ref.start;
      const e = this.ref.end ?? s;
      label += e !== s ? `:${s}-${e}` : `:${s}`;
    }
    label += rangeNote;
    const link = header.createEl("a", {
      cls: "codefile-link",
      text: label,
      href: "#"
    });
    link.addEventListener("click", (ev) => {
      ev.preventDefault();
      void this.plugin.app.workspace.openLinkText(
        file.path,
        this.ctx.sourcePath
      );
    });
  }
  renderError(msg) {
    this.containerEl.empty();
    this.containerEl.createDiv({
      cls: "codefile-error",
      text: `\u26A0 codefile: ${msg}`
    });
  }
};
function pickFence(content) {
  let longest = 0;
  const runs = content.match(/`+/g);
  if (runs) {
    for (const run of runs)
      longest = Math.max(longest, run.length);
  }
  return "`".repeat(Math.max(3, longest + 1));
}

// src/main.ts
var CodeFilePlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerMarkdownCodeBlockProcessor(
      "codefile",
      (source, el, ctx) => {
        const spec = this.resolveSpec(source, el, ctx);
        const ref = parseCodeFileSource(spec);
        ctx.addChild(new CodeFileChild(this, ctx, el, ref));
      }
    );
    this.addSettingTab(new CodeFileSettingTab(this.app, this));
  }
  /**
   * Get the spec string: prefer the block body (first non-empty line), else
   * read it off the fence info line after the `codefile` keyword.
   */
  resolveSpec(source, el, ctx) {
    const body = (source ?? "").trim();
    if (body) {
      const firstLine = body.split("\n").find((l) => l.trim().length > 0);
      if (firstLine)
        return firstLine.trim();
    }
    const info = ctx.getSectionInfo(el);
    if (info) {
      const fenceLine = info.text.split("\n")[info.lineStart] ?? "";
      return fenceLine.replace(/^[`~]{3,}\s*codefile\b/i, "").trim();
    }
    return "";
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data ?? {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};

/* nosourcemap */